Feature : conference between selective parties (#63) - version 1
voiceip/tinyphone pull request #71
Opened 2022-09-01 19:02 UTC by ploufs

2022-09-07 08:21 UTC, kingster requested changes
Thanks for the PR

Could you have a look at the comments? Also please fix the indentation error in the new function that was added.

2022-09-07 08:21 UTC, kingster commented on tinyphone/server.cpp
> +			});
Please fix this indentation error

2022-09-07 08:21 UTC, kingster commented on tinyphone/server.cpp
> +	CROW_ROUTE(app, "/calls/<int>/attendedtransfer/<int>")
`attended-transfer` would be better instead of a single word?

2022-09-07 08:21 UTC, kingster commented on tinyphone/phone.cpp
> +		const Call dest = *dest_call;
Is this required? 

Can't we just use this instead?

```
call->xferReplaces(*dest_call,prm);
```

2022-09-07 08:21 UTC, kingster commented on tinyphone/server.cpp
> +				});
Indentation issue.

2022-09-07 14:16 UTC, ploufs commented
The code is updated

2022-09-08 12:24 UTC, merged

2022-09-08 12:24 UTC, kingster commented
Thank you @ploufs !